### ISSUE TITLE
Cannot create new issue?

### ISSUE THREAD

**Issue by macaulay576** [pixeline/bugs#123]
I am unable to create a new issue. Clean install, new DB. Can create users and projects succesfully, just cannot add a new issue (causes Apache to crash).
Apache Error Log:
`[Wed Mar 29 18:19:36.093173 2017] [:error] [pid 7048:tid 1856] [client ::1:64450] PHP Fatal error: Cannot re-assign $this in C:\\xampp\\htdocs\\app\\application\\controllers\\project\\issue.php on line 291, referer: http://localhost/project/1`

I'm using XAMPP,
Windoze 7
Apache 2.4.25
MariaDB 10.1.21
PHP 5.6.30

**Comment by macaulay576** [comment]
FILE: C:\\xampp\\htdocs\\app\\application\\controllers\\project\\issue.php
Adjusted as follows;
#291	foreach ($TagsDiff as $ind => ~~$this~~ $val) {
#292	$TagNum = Tag::where('tag', '=', ~~$this~~ $val )->first(array('id','tag','bgcolor'));

**Comment by macaulay576** [comment]
Also changed these lines in the same file;
#306	foreach ($TagsDiff as $ind => ~~$this~~ $val) {
#307	$TagNum = Tag::where('tag', '=', ~~$this~~ $val )->first(array('id','tag','bgcolor'));

**Comment by Patriboom** [comment]
And everything works good, now ?

**Comment by Patriboom** [comment]
Thanks for that.  I was my mistake.

**Comment by Patriboom** [comment]
Your correct lines are now included into the program.

**Comment by macaulay576** [comment]
So far so good! Great app, BTW - I was trying to code something myself at first, as Mantis, Redmine, etc are all just too complex for my needs. #HighFive

**Comment by Patriboom** [comment]
From this, I transformed a bit the install process.
Now, you'll find only ONE MySQL structure file.
For those who will install using PHP tools, php server will read the unique SQL file.
For others: they will use the SQL file.

An other change:  the SQL file is now in the install sub-directory and named without any space in its name.  The new name is:  ./install/MySQL_DB_Schema.sql   (with underscores instead of spaces).
