### ISSUE TITLE
Attachments

### ISSUE THREAD

**Issue by Hazaels** [pixeline/bugs#179]
I just deleted the database, reinstalled bugs from scratch (latest version), configured and put to test.
The attachments are not working for me...
Sometimes I try to attach a file and it does nothing. 
Sometimes it does but the link is completely off... 
For example:

_site-example.com/bugs/uploads/1//tmp/phpp81jtO/freepaper-revision.jpg_

When it should be:

_site-example.com/bugs/uploads/freepaper-revision.jpg_

Do a test yourself... do it from scratch (new instalation and database)

**Comment by Patriboom** [comment]
Thanks again for your patience.
You gave me clue to correct this issue and also something else about the same topic.
You'll see that in latest version of 

- app/application/views/activity/attached-file.php
- app/application/views/project/issue/activity/attached-file.php
- app/application/views/project/issue/activity/comment.php
- app/application/views/project/issue/index.php

**Comment by Patriboom** [comment]
I close this issue and ask you to keep going with the issue number 161

https://github.com/pixeline/bugs/issues/161

**Comment by marcelloinfoweb** [comment]
I made the installation clean, downloaded the files, created a new database, did the procedure, which is different from the original project, it is missing files. After the entire installation process, I could not log in, the email or password does not access the system.

What is the username and password to access after installation is complete?

**Comment by Patriboom** [comment]
Hello Marcello, 

thanks for your patience.
Which files do you think are missing ? 
I've installed this version 3-4 times during July everthing was find.
Since then, I've took not a single file off.  Supprising comment.
I want it good and nice, so ... i'm listing to your, waiting for more details about your installation.

You were suposed to define your main-user name and password during the install process. There's no default root or admin name nor password.
