### ISSUE TITLE
Email format

### ISSUE THREAD

**Issue by Hazaels** [pixeline/bugs#180]
I have an issue with the email sent from Bugs:

The e-mails should be HTML formatted, right?

What I get is a email with HTML entities on it as you can see below (exact like that):

```
<p>New issue "Test 1" was submitted to "TEST" project and assigned to you.</p>

<p><p>test 1</p><br />
</p>

<p>Created by: Hazael of Ruben<br />
Find more information at: <a href="http://www.site-example/bugs/project/1/issue/2">http://www.site-example/bugs/project/1/issue/2</a></p>
<!--

<pre>
<h2>Issue</h2>

<h2>Project</h2>
</pre>
-->

```

**Comment by Patriboom** [comment]
Ouch!
PHPmailer is there to do that!
¿ Will it be easy to program the entire thing by hand ?

**Comment by Patriboom** [comment]
Seams to miss some headers.

**Comment by Patriboom** [comment]
I'm back on track, guys.  I've been out of computing for a while ( health  reasons ).
Please, Hazaels, let me know if your configuration file has  
'transport' => 'smtp',
or 
'transport' => 'app',


First option will work with the simple « sendmail » function from PHP
The second one should work with phpmailer.php librarie.

**Comment by wycky** [comment]
wish PHPmailer could do just plain text without necessarily sending the mail with HTML tags like sample below:

New issue "Test 1" was submitted to "TEST" project and assigned to you

test 1

Created by: Hazael of Ruben

Find more information at: "http://www.site-example/bugs/project/1/issue/2">http://www.site-example/bugs/project/1/issue/2


Any idea Patrick how to achieve this?

**Comment by wycky** [comment]
i got a solution think its by editing new_assigned_issue.php file (removing HTML tags)

**Comment by Patriboom** [comment]
Please, wycky, specify the line number you've modified.

That could be a nice option « HTML » format or « plain » format.
But for this, we must be able to produce a nice and clean HTML format.

**Comment by wycky** [comment]
modified line 1, 3, 5 and 6 by removing <p>....</p>, </br>, <a href.... and </a></p>

clean code 👍 
<?php echo sprintf(__('email.assignment'),$issue->title,$project->name); ?>.

<?php echo sprintf(__('email.created_by'),$issue->user->firstname . ' ' . $issue->user->lastname); ?>

<?php echo __('email.more_url'); ?><?php echo $issue->to(); ?>
  

Sample Email Result:

Issue "Test" in "IT Support" project has a new comment:

Submitted by: Emmanuel Ogola
Find more information at: http://localhost:81/RTS/project/3/issue/2

**Comment by wycky** [comment]
entire code atached on this file for your reference
![capture](https://user-images.githubusercontent.com/25264938/34148939-70e2ca6e-e4b4-11e7-9ca6-ee01ec605498.JPG)

and the result in the email attached on the second file below
![capture](https://user-images.githubusercontent.com/25264938/34148999-9ddcd488-e4b4-11e7-8c04-3865a7810588.JPG)

**Comment by wycky** [comment]
Also apply the same by removing the tags on all  the issue files i.e. update,comment, and change status files. i also removed the comments body on line three of new_assigned_issue.php file from being sent to the email since by the recipient going through the email notification, he/she may not bother to log into the bugs system to check the issue

**Comment by Patriboom** [comment]
May someone have a look on  lines 57 and 58 
of app/application/libraires/mail.php

`		$mail->ContentType = 'text/plain';
		$mail->IsHTML(false);
`

Those lines are in hard but must be built on variables.

**Comment by wycky** [comment]
Someone close this case, all of us interested in bugs project needs to have a positive mind towards improving this project for the benefit of all of us whether a solution was given to your issue or not, personally i cant sit and wait Patrick to fix everything for me. so lets stop pushing hard for maybe those unreachable implementations at the moment. Me am glad that all my past issues have found solutions to them thus focus forward. otherwise if we start throwing "stones" at each other we will not gain or learn anything from this project. Personally i like this project thanks and credit to the main developer however little or none i contribute

**Comment by Hazaels** [comment]
I am out of this project...

**Comment by Patriboom** [comment]
Thanks wycky.

**Comment by wycky** [comment]
Anytime

**Comment by Patriboom** [comment]
Hello everyone, 
I've worked on HTML format emailing and saved into a new branch named  Work2018.
It is supposed to
 - send proper plain text
 - send HTML email with a plain text as alternative part.

Please try it and let me know.
To turn the HTML option ON, you'll need to edit the **config.app.php** file, adding the following lines
```
		/*
		* Final delivery format
		* Default: text/plain
		* 'text/plain' or 'html'  must be lower case
		*/
		'plainHTML' => 'text/plain',
		'linelenght' => 80

```

**Don't forget** to edit the line 79, adding a comma to its end like:
`		'encoding' => 'UTF-8',
`
