### ISSUE TITLE
Only Administrators can create issues

### ISSUE THREAD

**Issue by chaoscommander** [pixeline/bugs#209]
I set up an instance of Bugs on my server, created one Administrator and one Manager. Now the Manager was unable to create issues - she received the non-helpful message "Whoops! Something went wrong!". After I made her an Administrator, she also could create issues.

Didn't find any helpful logs so far, maybe I looked in the wrong place. Willing to supply more info, if you can tell me what you need.

Running v1.5 - release 1.3.2 on Apache 2.4.25, Debian 9.3

**Comment by Patriboom** [comment]
That is pretty strange, but sounds like something I already red around here.
Any solutions, other ? 

You're supposed to be able to manage attribute for each user, for each project.  We all do that using the same program.  Nothing has been changed in that since very, very long; before I get involved in.

I'll try to repeat the same as you, and find what's wrong it that.

**Comment by wycky** [comment]
I suggest get  again the project files (download) and drop every Bugs file on your server and set up afresh, thank me later

**Comment by Patriboom** [comment]
Good news ... it will be easier.
I'll try to find my jQuery config, because on my system it doesn't work.  Doing that, I'll set the path for those who will encounter the same problem.

**Comment by Patriboom** [comment]
Does anyone have time to build a « step by step » guide for new installation and startup?
Once the system is installed, what to do then ? 
- Create a project
- Create an user
- Assign a project to user
- Create first issue
- and so on ....

**Comment by wycky** [comment]
This too should be closed
