### ISSUE TITLE
Item state in "ToDos" not synced with item state in "Your List".

### ISSUE THREAD

**Issue by rickbsgu** [pixeline/bugs#32]
I like the direction this is going & what I'm seeing may be on your timeline, already.

That said, the states aren't working real well.

I would expect that:
- When I send an item to the ToDo list, the 'send to' button becomes disabled, or disappears, or does somethine other than regenerate and present, again.  (If you hit it again, which you shouldn't be able to do you get a system language dialog).
- Need  built-in 'In Progress' tag.  If item state changed to 'In Progress', it moves to the 'In Progress' ToDo.  Vice versa, as well.
- Same behavior with 'Closed' state.

thanks
rickb

**Comment by Patriboom** [comment]
I've have the same issue, but also ideas to fix it.
What about a percentage of work done ?
According to such percentage, work will be presented in « Open », « In Progress », « Testing » or « Done » section.

In « Done » section, may we list  all last 10 tickets
Do you prefer the la 10 (or so) days tickets ? 
Otherwise, all tickets done ( maybe hundreds) will appear.

About percentage. I had in mind:
Not open yet: 0%
Just red, nothing done: 10%
In progress: from 11% to 89%
Testing: from 90% to 99%
Closed: 100%

**Comment by Patriboom** [comment]
I worked on that issue and it is fixed.  Only wait for the branch merge.  It will be done soon.

**Comment by Patriboom** [comment]
Because I don't know how to make to work an efficient pull request, modifications are available on  https://github.com/Patriboom/bugs
