### ISSUE TITLE
www-data

### ISSUE THREAD

**Issue by oluwanbejr** [pixeline/bugs#837]
set www-data ( CHOWN -R www-data:www-data ) as owner of the Bugs's main directory and sub-directories

Please how do I do the above on cPanel

Thanks!

**Comment by Patriboom** [comment]
I think you can not throw cPanel.
Meanwhile, you probably don't need to do so either because www-data has greater permissions than  any « user ».
But, if still it doesn't work, you can change directory permission throw cPanel that way:

- In cPanel, open the « File manager »
- show the directory you want to work on
- select the BUGS directory (single click)
- on top cPanel menu, you'll find « Permissions » button
-manage the permissions accordinly to your needs.

**Comment by oluwanbejr** [comment]
Thanks for you response.

 It worked!
